wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.0
    framework: xgboost
    huggingface_version: 4.35.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699432476.29919
    t:
      1:
      - 1
      - 5
      - 6
      - 11
      - 41
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 6
      - 11
      - 41
      - 49
      - 53
      - 55
      3:
      - 23
      4: 3.10.12
      5: 0.16.0
      6: 4.35.0
      8:
      - 5
      13: linux-x86_64
